import type { Metadata } from "next";

import "./globals.css";
import Nav from "./ui/Nav";
import Provider from "./ui/Provider";
import { ThemeProvider } from "./utils/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" href="/assets/images/logo.svg" sizes="any" />
      <body className={``}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange
        >
          <Provider>
            <div className="main dark:dark_main">
              <div className="gradient"></div>
            </div>

            <main className="app">
              <Nav />
              {children}
            </main>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
